# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf05a3434182c710f9e29d6b76472350b3946661d96e225b9c43a320c4a580e3674f259df909b9b4bad16c9ee262dfc0faf0022fcad258eba30802786007042

test:
  secret_key_base: 2e8bd403afb0fceceb7a3cd31cafb4d433fc58437dc018477a3a26e7f256caa14d2e544e6b0b541d9f0302e157e28a8230f92fcd097a867ee1bcd18bf8fb86e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
